#' Create climatic suitability change map
#'
#' Automate the full workflow for generating a species climatic
#' suitability change trend map, essentially a view of suitability trend
#' acceleration and deceleration.
#'
#' @details
#' This function is part of the rENM framework's processing pipeline
#' and operates within the project directory structure defined by
#' rENM_project_dir().
#'
#' \strong{Pipeline context}
#' The function automates the full workflow for generating a species
#' climatic suitability change trend map. It first calls
#' \code{find_suitability_change_trend()} to compute and save the raster
#' files representing per-pixel trends (Theil-Sen slopes), and then
#' calls \code{plot_suitability_change_trend()} to visualize these as a
#' map and save a .png image in the project directory.
#'
#' The resulting map depicts areas of increasing or decreasing
#' suitability change rate (acceleration or deceleration) across the
#' species range.
#'
#' \strong{Inputs}
#' \itemize{
#'   \item Species alpha code used to derive both input raster and
#'   output map paths.
#'   \item Optional raster input provided as a file path or SpatRaster.
#' }
#'
#' \strong{Outputs}
#' \itemize{
#'   \item Raster layers generated by
#'   \code{find_suitability_change_trend()}.
#'   \item Map visualization generated by
#'   \code{plot_suitability_change_trend()}.
#'   \item PNG image written to the project directory.
#' }
#'
#' \strong{Methods}
#' \itemize{
#'   \item Step 1: Compute raster layers using
#'   \code{find_suitability_change_trend(<alpha_code>)} to create:
#'   \code{<project_dir>/runs/<alpha_code>/Trends/suitability/}
#'   \code{<alpha_code>-Suitability-Change-Trend.tif}
#'   or
#'   \code{<alpha_code>-Suitability-Change-Trend.asc}
#'   \item Step 2: Plot suitability change using
#'   \code{plot_suitability_change_trend(<alpha_code>, raster_file)}
#'   \item Step 3: Save map to:
#' }
#' \preformatted{
#' <project_dir>/runs/<alpha_code>/Trends/suitability/<alpha_code>-Suitability-Change-Trend.png
#' }
#'
#' If no raster path is provided, the function automatically uses the
#' default .tif (preferred) or .asc raster produced by
#' \code{find_suitability_change_trend()}.
#'
#' \strong{Data requirements}
#' The function assumes existence of raster outputs in:
#' \code{<project_dir>/runs/<alpha_code>/Trends/suitability/}
#'
#' @param alpha_code Character. Four-letter species code (e.g., "CASP").
#' Used to derive both the input raster and output map paths.
#' @param raster_file Character, SpatRaster. Optional path to a raster
#' (.tif or .asc) or a terra SpatRaster containing suitability change
#' trend values. If not supplied, the function automatically computes
#' and loads the default raster file from:
#' \code{<project_dir>/runs/<alpha_code>/Trends/suitability/}
#' \code{<alpha_code>-Suitability-Change-Trend.tif}
#' or
#' \code{<alpha_code>-Suitability-Change-Trend.asc}
#'
#' @return
#' Character vector of length one containing the full file path to the
#' saved .png map.
#' Side effects:
#' \itemize{
#'   \item Raster files are generated if not already present.
#'   \item PNG map file is written to disk.
#'   \item Log entries are appended to:
#'   \code{<project_dir>/runs/<alpha_code>/_log.txt}
#' }
#'
#' @importFrom ggplot2 theme element_rect element_text ggsave
#'
#' @examples
#' \dontrun{
#' # Full automatic workflow -- computes trend and saves map
#' create_suitability_change_map("CASP")
#'
#' # Use a preexisting raster file if already available
#' create_suitability_change_map(
#'   "CASP",
#'   "runs/CASP/Trends/suitability/CASP-Suitability-Change-Trend.tif"
#' )
#' }
#'
#' @export
create_suitability_change_map <- function(alpha_code, raster_file = NULL) {
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required.", call. = FALSE)
  }

  if (!exists("rENM_project_dir", mode = "function")) {
    stop("Function `rENM_project_dir()` must be available (e.g., exported by this package).")
  }

  project_dir <- rENM_project_dir()

  t_start <- Sys.time()
  code <- toupper(alpha_code)

  # --- Step 1: Run find_suitability_change_trend() (from this package/namespace) ---
  message(
    "Running find_suitability_change_trend() to generate suitability ",
    "change trend rasters..."
  )
  find_suitability_change_trend(code)

  # --- Step 2: Determine raster file if not provided ---
  if (is.null(raster_file)) {
    base_dir <- file.path(
      project_dir, "runs", code, "Trends", "suitability"
    )
    tif_path <- file.path(
      base_dir,
      sprintf("%s-Suitability-Change-Trend.tif", code)
    )
    asc_path <- file.path(
      base_dir,
      sprintf("%s-Suitability-Change-Trend.asc", code)
    )

    if (file.exists(tif_path)) {
      raster_file <- tif_path
      message("Using generated raster: ", raster_file)
    } else if (file.exists(asc_path)) {
      raster_file <- asc_path
      message("Using generated raster: ", raster_file)
    } else {
      stop(
        "No .tif or .asc raster found after running ",
        "find_suitability_change_trend().",
        call. = FALSE
      )
    }
  }

  # --- Step 3: Generate base plot via plot_suitability_change_trend() ---
  res <- plot_suitability_change_trend(code, raster_file)
  gp  <- res$plot

  # Standardize appearance
  gp <- gp +
    ggplot2::theme(
      plot.background  = ggplot2::element_rect(fill = "white", color = NA),
      panel.background = ggplot2::element_rect(fill = "white", color = NA),
      plot.title       = ggplot2::element_text(size = 28, face = "bold"),
      plot.subtitle    = ggplot2::element_text(size = 20),
      legend.text      = ggplot2::element_text(size = 15),
      legend.title     = ggplot2::element_text(size = 15),
      axis.title       = ggplot2::element_text(size = 20, face = "plain"),
      axis.text        = ggplot2::element_text(size = 18)
    )

  # --- Step 4: Build output directory ---
  out_dir <- file.path(
    project_dir, "runs", code, "Trends", "suitability"
  )
  if (!dir.exists(out_dir)) {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  }

  # --- Step 5: Derive <NAME> from input raster filename ---
  name_hint <- "Suitability-Change-Trend"
  if (is.character(raster_file) && length(raster_file) == 1L) {
    fbase <- basename(raster_file)
    stem <- tryCatch(
      tools::file_path_sans_ext(fbase),
      error = function(e) tools::file_path_sans_ext(fbase)
    )
    if (grepl(paste0("^", code, "-"), stem, ignore.case = TRUE)) {
      name_part <- sub(
        paste0("^", code, "-"),
        "",
        stem,
        ignore.case = TRUE
      )
      if (nzchar(name_part)) name_hint <- name_part
    } else {
      parts <- strsplit(stem, "-", fixed = TRUE)[[1]]
      if (length(parts) >= 2) {
        name_hint <- paste(parts[-1], collapse = "-")
      } else if (nzchar(stem)) {
        name_hint <- stem
      }
    }
    name_hint <- gsub("[^A-Za-z0-9._-]+", "_", name_hint)
    if (!nzchar(name_hint)) name_hint <- "Suitability-Change-Trend"
  }

  # --- Step 6: Save PNG map ---
  out_file <- file.path(out_dir, sprintf("%s-%s.png", code, name_hint))
  ggplot2::ggsave(
    filename  = out_file,
    plot      = gp,
    width     = 1000,
    height    = 750,
    units     = "px",
    dpi       = 72,
    pointsize = 15,
    bg        = "white"
  )

  cat("------------------------------------------------------------------------\n")
  cat(sprintf("create_suitability_change_map(): Completed for %s\n", code))
  cat(sprintf("Derived name: %s\n", name_hint))
  cat(sprintf("Raster file: %s\n", raster_file))
  cat(sprintf("Saved map: %s\n", out_file))

  # ---- eBird-standard log append --------------------------------------------
  t_end <- Sys.time()
  elapsed <- difftime(t_end, t_start, units = "secs")
  s <- as.numeric(elapsed)
  hh <- sprintf("%02d", s %/% 3600); s <- s %% 3600
  mm <- sprintf("%02d", s %/% 60);   ss <- sprintf("%02d", round(s %% 60))
  fmt_elapsed <- paste0(hh, ":", mm, ":", ss)

  log_file <- file.path(project_dir, "runs", code, "_log.txt")

  sep_line <- paste(rep("-", 72), collapse = "")
  header   <- "Processing summary (create_suitability_change_map)"
  ts_str   <- format(t_end, "%Y-%m-%d %H:%M:%S %Z")
  f <- function(k, v) sprintf("%-18s : %s", k, v)

  outputs <- c(out_file)
  log_block <- c(
    "",
    sep_line,
    header,
    f("Timestamp",     ts_str),
    f("Alpha code",    code),
    f("Raster source", raster_file),
    f("Outputs saved", length(outputs)),
    vapply(outputs, function(x) paste0(" - ", x), character(1)),
    f("Total elapsed", fmt_elapsed),
    ""
  )

  try({
    dir.create(dirname(log_file), recursive = TRUE, showWarnings = FALSE)
    cat(paste0(log_block, collapse = "\n"), file = log_file, append = TRUE)
  }, silent = TRUE)

  invisible(out_file)
}
