#' Save suitability trend plot with entroids to File
#'
#' Generate a climatic suitability trend map with centroid shift overlay
#' and save it as a PNG image using standardized dimensions and styling.
#' The function wraps plot generation and ensures consistent output.
#'
#' @details
#' This function is part of the rENM framework's processing pipeline
#' and operates within the project directory structure defined by
#' rENM_project_dir().
#'
#' \strong{Inputs}
#' \itemize{
#'   \item Climatic suitability trend raster:
#'   \code{<project_dir>/runs/<alpha_code>/Trends/suitability/}
#'   \code{<alpha_code>-Suitability-Trend.tif}
#'   or
#'   \code{<project_dir>/runs/<alpha_code>/Trends/suitability/}
#'   \code{<alpha_code>-Suitability-Trend.asc}
#'   \item Plot generated by \code{plot_trend_with_centroids()}
#' }
#'
#' \strong{Outputs}
#' \itemize{
#'   \item PNG image written to:
#'   \code{<project_dir>/runs/<alpha_code>/Trends/suitability/}
#'   \code{<alpha_code>-Suitability-Trend-With-Centroids.png}
#' }
#'
#' \strong{Methods}
#' \itemize{
#'   \item Calls \code{plot_trend_with_centroids()} to generate the plot
#'   \item Applies standardized theme overrides for font sizes and white
#'   background
#'   \item Saves output using fixed dimensions (1000 x 750 pixels at
#'   72 dpi)
#' }
#'
#' \strong{Data requirements}
#' \itemize{
#'   \item Requires \code{plot_trend_with_centroids()} and its
#'   dependencies (e.g., \code{get_species_info()}) to be available in
#'   the package namespace
#'   \item If \code{raster_file} is not provided, the underlying plotting
#'   function auto-discovers the raster by searching:
#'   \itemize{
#'     \item \code{<project_dir>/runs/<alpha_code>/Trends/suitability/}
#'     \code{<alpha_code>-Suitability-Trend.tif}
#'     \item \code{<project_dir>/runs/<alpha_code>/Trends/suitability/}
#'     \code{<alpha_code>-Suitability-Trend.asc}
#'   }
#' }
#'
#' @param alpha_code Character. Four-letter banding code for the species.
#' @param raster_file Character, SpatRaster. NULL (default) to
#' auto-discover, a file path to a raster (.tif or .asc), or a
#' \code{terra::SpatRaster}. If NULL, .tif is preferred over .asc.
#' @param zero_band_frac Numeric. Neutral band fraction for the diverging
#' palette. Defaults to 0.80 to match
#' \code{plot_trend_with_centroids()} default.
#'
#' @return Invisibly returns a Character file path with:
#' \itemize{
#'   \item The full path to the saved PNG file
#' }
#'
#' Side effects:
#' \itemize{
#'   \item Creates output directories if they do not exist
#'   \item Writes a PNG file to disk
#'   \item Prints status messages to the console
#' }
#'
#' @importFrom ggplot2 ggsave theme element_rect element_text
#'
#' @examples
#' \dontrun{
#'   save_trend_plot_with_centroids("CASP")
#' }
#'
#' @seealso
#' \code{plot_trend_with_centroids()}
#'
#' @export
save_trend_plot_with_centroids <- function(alpha_code,
                                           raster_file   = NULL,
                                           zero_band_frac = 0.80) {
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required.", call. = FALSE)
  }

  # Normalize code
  code <- toupper(alpha_code)

  # Project directory
  project_dir <- rENM_project_dir()

  # --- Generate plot (with centroids) ---------------------------------------
  # If raster_file is NULL, plot_trend_with_centroids() will auto-discover
  res <- plot_trend_with_centroids(
    alpha_code      = code,
    raster_file     = raster_file,
    zero_band_frac  = zero_band_frac
  )

  gp <- res$plot

  # Apply standardized theme overrides for font sizes & white background
  gp <- gp +
    ggplot2::theme(
      plot.background  = ggplot2::element_rect(fill = "white", color = NA),
      panel.background = ggplot2::element_rect(fill = "white", color = NA),
      plot.title       = ggplot2::element_text(size = 25, face = "bold"),
      legend.text      = ggplot2::element_text(size = 15),
      legend.title     = ggplot2::element_text(size = 15),
      axis.title       = ggplot2::element_text(size = 20, face = "plain"),
      axis.text        = ggplot2::element_text(size = 18)
    )

  # Build output directory and file path
  out_dir <- file.path(project_dir, "runs", code, "Trends", "suitability")
  if (!dir.exists(out_dir)) {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  }

  out_file <- file.path(out_dir, paste0(code, "-Suitability-Trend-With-Centroids.png"))

  # Save PNG with exact pixel dimensions and resolution
  ggplot2::ggsave(
    filename  = out_file,
    plot      = gp,
    width     = 1000,
    height    = 750,
    units     = "px",
    dpi       = 72,
    pointsize = 15,
    bg        = "white"
  )

  cat("------------------------------------------------------------------------\n")
  cat(sprintf("save_trend_plot_with_centroids(): Saved plot for %s\n", code))
  cat(sprintf("Output file: %s\n", out_file))

  invisible(out_file)
}
