#' Finds bioclimatic from weighted centroids
#'
#' Computes geodesic distance, initial bearing, and velocity between
#' 1980 and 2020 weighted centroids derived from prior analyses.
#' Outputs are written to project directories and appended to logs.
#'
#' @details
#' This function is part of the rENM framework's processing pipeline
#' and operates within the project directory structure defined by
#' rENM_project_dir().
#'
#' \strong{Pipeline context}
#' Computes bioclimatic displacement between two temporal endpoints
#' using weighted centroids generated by
#' \code{find_weighted_centroid(alpha_code)}.
#'
#' \strong{Inputs}
#' \itemize{
#'   \item Weighted centroid CSV files located in:
#'   \code{<project_dir>/runs/<alpha_code>/TimeSeries/<year>/model/}
#'   \item If missing and \code{auto_compute_missing = TRUE}, centroids
#'   are computed inline from prediction rasters
#' }
#'
#' \strong{Outputs}
#' \itemize{
#'   \item \code{<project_dir>/runs/<alpha_code>/Trends/centroids/}
#'   \code{<alpha_code>-Bioclimatic-Velocity.csv}
#'   \item Log appended to:
#'   \code{<project_dir>/runs/<alpha_code>/}
#'   \code{_log.txt}
#' }
#'
#' \strong{Methods}
#' \itemize{
#'   \item Distance computed using \code{geosphere::distHaversine}
#'   \item Bearing computed using \code{geosphere::bearing}
#'   \item Bearing normalized to (0, 360)
#'   \item Velocity computed as distance divided by 40 years
#' }
#'
#' \strong{Data requirements}
#' \itemize{
#'   \item Centroids must be in WGS84 longitude/latitude coordinates
#'   \item Raster inputs must be readable by \code{terra::rast}
#' }
#'
#' If either 1980 or 2020 centroid is missing and
#' \code{auto_compute_missing = TRUE}, this function computes it inline
#' without external logging, writes the centroid CSV, and proceeds.
#'
#' \strong{Side effects}
#' Writes the velocity CSV and appends a structured log block. The
#' function sanitizes the appended portion of \code{_log.txt} to remove
#' extraneous \code{find_weighted_centroid} blocks while preserving all
#' prior content.
#'
#' @param alpha_code Character. Four-letter banding code for the species
#' (e.g., "CASP").
#' @param auto_compute_missing Logical. If TRUE (default), attempts to
#' compute missing 1980 or 2020 centroids inline without logging side
#' effects.
#' @param verbose Logical. If TRUE (default), prints diagnostic messages.
#'
#' @return Invisibly returns a data.frame with the following structure:
#' \itemize{
#'   \item start_lon: Numeric. 1980 centroid longitude (WGS84).
#'   \item start_lat: Numeric. 1980 centroid latitude (WGS84).
#'   \item end_lon: Numeric. 2020 centroid longitude (WGS84).
#'   \item end_lat: Numeric. 2020 centroid latitude (WGS84).
#'   \item distance_km: Numeric. Great-circle distance in kilometers.
#'   \item bearing_deg: Numeric. Initial bearing (degrees from North,
#'   0-360).
#'   \item velocity_km_per_yr: Numeric. Distance divided by 40 years.
#' }
#'
#' Side effects include:
#' \itemize{
#'   \item Writing CSV output to the Trends/centroids directory
#'   \item Appending a structured log entry to _log.txt
#'   \item Conditional inline generation of missing centroid CSV files
#' }
#'
#' @importFrom utils write.csv read.csv
#' @importFrom geosphere distHaversine bearing
#'
#' @examples
#' \dontrun{
#' find_bioclimatic_velocity("CASP")
#' }
#'
#' @export
find_bioclimatic_velocity <- function(alpha_code,
                                      auto_compute_missing = TRUE,
                                      verbose = TRUE) {

  ## ---------- Basic checks ----------
  if (!is.character(alpha_code) || length(alpha_code) != 1L || nchar(alpha_code) != 4L) {
    stop("alpha_code must be a 4-letter character string, e.g., 'CASP'.")
  }

  # format elapsed as HH:MM:SS.ss
  .fmt_hms <- function(sec) {
    h <- floor(sec / 3600)
    m <- floor((sec %% 3600) / 60)
    s <- sec - h * 3600 - m * 60
    sprintf("%02d:%02d:%05.2f", h, m, s)
  }
  t_start <- proc.time()[["elapsed"]]

  ## ---------- Paths ----------
  project_dir <- rENM_project_dir()

  species_root <- normalizePath(
    file.path(project_dir, "runs", alpha_code),
    winslash = "/", mustWork = FALSE
  )
  if (!dir.exists(species_root)) {
    dir.create(species_root, recursive = TRUE, showWarnings = FALSE)
  }

  out_dir <- normalizePath(
    file.path(species_root, "Trends", "centroids"),
    winslash = "/", mustWork = FALSE
  )
  if (!dir.exists(out_dir)) {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  }

  out_csv  <- file.path(out_dir, sprintf("%s-Bioclimatic-Velocity.csv", alpha_code))
  log_path <- file.path(species_root, "_log.txt")
  if (!file.exists(log_path)) file.create(log_path)

  # snapshot the current log so we can sanitize only what gets appended now
  pre_lines <- tryCatch(readLines(log_path, warn = FALSE), error = function(e) character(0))
  pre_n     <- length(pre_lines)

  ## ---------- Helpers (no logging side-effects) ----------
  read_centroid_csv <- function(year) {
    model_dir <- file.path(project_dir, "runs", alpha_code, "TimeSeries", year, "model")
    in_csv    <- file.path(model_dir, sprintf("%s-%s-Centroid.csv", alpha_code, year))
    if (!file.exists(in_csv)) return(NULL)

    df <- try(utils::read.csv(in_csv, stringsAsFactors = FALSE), silent = TRUE)
    if (inherits(df, "try-error") || !all(c("lon", "lat") %in% names(df))) return(NULL)

    list(
      lon  = as.numeric(df$lon[1]),
      lat  = as.numeric(df$lat[1]),
      path = in_csv
    )
  }

  # inline centroid compute using terra (no logging)
  inline_compute_centroid <- function(year) {
    if (!requireNamespace("terra", quietly = TRUE)) {
      stop("Package 'terra' is required to compute missing centroids: install.packages('terra').")
    }

    base_dir <- file.path(project_dir, "runs", alpha_code, "TimeSeries", year, "model")
    stem     <- sprintf("%s-%s-Prediction", alpha_code, year)
    f_tif    <- file.path(base_dir, paste0(stem, ".tif"))
    f_asc    <- file.path(base_dir, paste0(stem, ".asc"))
    cand     <- if (file.exists(f_tif)) f_tif else if (file.exists(f_asc)) f_asc else NA_character_
    if (is.na(cand)) return(NULL)

    r <- try(terra::rast(cand), silent = TRUE)
    if (inherits(r, "try-error")) return(NULL)

    if (!terra::is.lonlat(r)) r <- terra::project(r, "EPSG:4326")
    df <- terra::as.data.frame(r, xy = TRUE, na.rm = TRUE)
    if (!nrow(df)) return(NULL)

    val_col <- setdiff(names(df), c("x", "y"))
    if (length(val_col) != 1L) return(NULL)

    w <- df[[val_col]]
    w[!is.finite(w)] <- NA
    keep <- !is.na(w)
    if (!any(keep)) return(NULL)

    xs <- df$x[keep]
    ys <- df$y[keep]
    w  <- w[keep]
    wsum <- sum(w)
    if (!is.finite(wsum) || wsum == 0) return(NULL)

    lon <- sum(xs * w) / wsum
    lat <- sum(ys * w) / wsum

    if (!dir.exists(base_dir)) {
      dir.create(base_dir, recursive = TRUE, showWarnings = FALSE)
    }
    out_centroid <- file.path(base_dir, sprintf("%s-%s-Centroid.csv", alpha_code, year))
    utils::write.csv(data.frame(lon = lon, lat = lat), out_centroid, row.names = FALSE)

    list(lon = lon, lat = lat, path = out_centroid)
  }

  ## ---------- Load endpoints; compute inline if missing ----------
  c1980 <- read_centroid_csv(1980L)
  c2020 <- read_centroid_csv(2020L)

  missing_years <- c(
    if (is.null(c1980)) 1980L else NULL,
    if (is.null(c2020)) 2020L else NULL
  )

  if (length(missing_years) && isTRUE(auto_compute_missing)) {
    if (isTRUE(verbose)) {
      message(
        "Computing missing centroid year(s) inline (no logging): ",
        paste(missing_years, collapse = ", ")
      )
    }
    for (yy in missing_years) {
      tmp <- inline_compute_centroid(yy)
      if (yy == 1980L) c1980 <- tmp
      if (yy == 2020L) c2020 <- tmp
    }
  }

  final_missing <- c(
    if (is.null(c1980)) 1980L else NULL,
    if (is.null(c2020)) 2020L else NULL
  )
  if (length(final_missing)) {
    stop(
      "Missing centroid CSV for year(s): ",
      paste(final_missing, collapse = ", "),
      ". Generate them first (e.g., via your centroid pipeline)."
    )
  }

  start_lon <- c1980$lon
  start_lat <- c1980$lat
  end_lon   <- c2020$lon
  end_lat   <- c2020$lat

  if (isTRUE(verbose)) {
    message(sprintf("1980 centroid: lon=%.6f lat=%.6f", start_lon, start_lat))
    message(sprintf("2020 centroid: lon=%.6f lat=%.6f", end_lon, end_lat))
  }

  ## ---------- Compute metrics ----------
  distance_km <- as.numeric(
    distHaversine(c(start_lon, start_lat), c(end_lon, end_lat))
  ) / 1000

  bearing_deg <- (bearing(c(start_lon, start_lat),
                          c(end_lon, end_lat)) + 360) %% 360

  velocity_km_per_yr <- distance_km / (2020 - 1980)

  ## ---------- Write velocity CSV ----------
  out_df <- data.frame(
    start_lon          = start_lon,
    start_lat          = start_lat,
    end_lon            = end_lon,
    end_lat            = end_lat,
    distance_km        = distance_km,
    bearing_deg        = bearing_deg,
    velocity_km_per_yr = velocity_km_per_yr
  )
  utils::write.csv(out_df, out_csv, row.names = FALSE)
  if (isTRUE(verbose)) message("Saved: ", out_csv)

  ## ---------- Append our log block ----------
  ts      <- format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")
  elapsed <- proc.time()[["elapsed"]] - t_start

  block <- c(
    "",
    "------------------------------------------------------------------------",
    "Processing summary (find_bioclimatic_velocity)",
    sprintf("Timestamp:          %s", ts),
    sprintf("Alpha code:         %s", alpha_code),
    "Years considered:    1980-2020",
    "Completed:          1",
    "Failed:             0",
    sprintf("Total elapsed:      %s (%.2f s)", .fmt_hms(elapsed), elapsed),
    sprintf("Outputs saved:      %s-Bioclimatic-Velocity.csv", alpha_code),
    "Results:",
    sprintf("  Distance (km):    %.3f", distance_km),
    sprintf("  Bearing (deg):    %.2f", bearing_deg),
    sprintf("  Velocity (km/yr): %.4f", velocity_km_per_yr),
    "Per-year status:",
    sprintf("  1980  status=ok lon=%.6f lat=%.6f notes=-", start_lon, start_lat),
    sprintf("  2020  status=ok lon=%.6f lat=%.6f notes=-", end_lon, end_lat)
  )

  con <- file(log_path, open = "a", encoding = "UTF-8")
  on.exit(close(con), add = TRUE)
  writeLines(block, con, sep = "\n", useBytes = TRUE)
  flush(con)

  ## ---------- Sanitize just-appended region ----------
  post_lines <- tryCatch(readLines(log_path, warn = FALSE), error = function(e) character(0))
  if (length(post_lines) > pre_n) {
    appended <- post_lines[(pre_n + 1L):length(post_lines)]
    dash     <- "------------------------------------------------------------------------"
    remove_idx <- rep(FALSE, length(appended))
    starts     <- which(appended == dash)
    if (length(starts)) {
      for (s in starts) {
        if (s + 1L <= length(appended) &&
            grepl("^Processing summary \\(find_weighted_centroid\\)$", appended[s + 1L])) {
          next_dash <- starts[which(starts > s)][1]
          e         <- if (is.na(next_dash)) length(appended) else (next_dash - 1L)
          remove_idx[s:e] <- TRUE
        }
      }
    }
    if (any(remove_idx)) {
      new_tail    <- appended[!remove_idx]
      final_lines <- c(pre_lines, new_tail)
      writeLines(final_lines, log_path, sep = "\n", useBytes = TRUE)
      if (isTRUE(verbose)) message("Sanitized extraneous centroid log blocks from this run.")
    }
  }

  invisible(out_df)
}
