#' Plot suitability trend map for a species
#'
#' Creates a publication-ready map of climatic suitability trend values
#' (positive = increasing suitability; negative = decreasing) using a
#' diverging color scale and overlaying geographic reference layers.
#'
#' @details
#' This function is part of the rENM framework's processing pipeline
#' and operates within the project directory structure defined by
#' rENM_project_dir().
#'
#' \strong{Inputs}:
#' A suitability trend raster is required, either as a file path or an
#' in-memory raster object. The raster typically corresponds to outputs
#' generated by find_suitability_trend().
#'
#' Species range information is retrieved using \code{get_species_info()}
#' via the GAP.RANGE field stored in:
#'
#' \code{<rENM_project_dir()>/data/}
#' \code{_species.csv}
#'
#' and loaded from:
#'
#' \code{<rENM_project_dir()>/data/shapefiles/}
#' \code{<GAP.RANGE>/<GAP.RANGE>.shp}
#'
#' U.S. state boundaries are loaded from:
#'
#' \code{<rENM_project_dir()>/data/shapefiles/}
#' \code{tl_2012_us_state/tl_2012_us_state.shp}
#'
#' \strong{Outputs}:
#' Returns a ggplot object representing the suitability trend surface
#' with overlaid vector boundaries. No files are written by this function.
#'
#' \strong{Methods}:
#' The raster is visualized using a red-white-green diverging palette
#' centered at zero, where negative values indicate decreasing suitability
#' and positive values indicate increasing suitability. Color limits are
#' selected symmetrically using the (2, 98) percent quantile range to
#' reduce the influence of outliers.
#'
#' Vector layers (states and species range) are reprojected to the raster
#' CRS when it is defined to ensure spatial alignment.
#'
#' \strong{Data requirements}:
#' The raster must contain at least one non-NA cell. Cells are extracted
#' and plotted in coordinate space. If no valid cells are present, the
#' function will stop with an error.
#'
#' @param alpha_code Character. Four-letter species code (e.g., "CASP"),
#'   used in the plot title and for species range lookup.
#' @param raster_file Character, SpatRaster, or Raster. A suitability
#'   trend raster provided either as a file path readable by terra::rast()
#'   or as an in-memory raster object.
#' @param zero_band_frac Numeric. Value in (0, 1) controlling the width of
#'   the neutral region around zero in the color scaling. Values closer to
#'   1 produce a narrower neutral band. Values are clipped to (0, 0.9).
#'
#' @return Invisibly returns a List with the following components:
#' \itemize{
#'   \item plot: ggplot object representing the trend map
#'   \item lims: Numeric vector of length 2 defining color scale limits
#'   \item n_cells: Integer number of non-NA raster cells plotted
#' }
#'
#' Side effects:
#' \itemize{
#'   \item Writes progress messages to the console
#' }
#'
#' @importFrom terra rast vect crs same.crs project ext nlyr as.data.frame
#' @importFrom sf st_as_sf st_crs
#' @importFrom ggplot2 ggplot geom_raster aes geom_sf scale_fill_gradient2 labs
#'   coord_sf theme_minimal theme element_rect element_line element_text
#' @importFrom stats quantile
#' @importFrom utils globalVariables
#'
#' @examples
#' \dontrun{
#'   plot_trend(
#'     "CASP",
#'     file.path(
#'       rENM_project_dir(),
#'       "runs", "CASP", "Trends", "suitability",
#'       "CASP-Suitability-Trend.tif"
#'     )
#'   )
#' }
#'
#' @seealso [find_suitability_trend()], [save_trend_plot()],
#'   [get_species_info()]
#'
#' @export
plot_trend <- function(alpha_code, raster_file, zero_band_frac = 0.80) {

  ## --------------------------- Input checks ------------------------------- ##
  if (!is.character(alpha_code) || length(alpha_code) != 1L || nchar(alpha_code) != 4L) {
    stop("`alpha_code` must be a single four-letter string, e.g. 'CASP'.", call. = FALSE)
  }
  if (!requireNamespace("terra", quietly = TRUE)) {
    stop("Package 'terra' is required.", call. = FALSE)
  }
  if (!requireNamespace("sf", quietly = TRUE)) {
    stop("Package 'sf' is required.", call. = FALSE)
  }
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required.", call. = FALSE)
  }

  code <- toupper(alpha_code)

  ## ------------------------ Species info / shapefile ---------------------- ##
  if (!exists("get_species_info", mode = "function")) {
    stop("Internal helper `get_species_info()` not found. Is rENM.core loaded?", call. = FALSE)
  }

  si <- try(get_species_info(code), silent = TRUE)
  if (inherits(si, "try-error") || is.null(si)) {
    stop("get_species_info() failed for alpha_code: ", code)
  }
  if (!("GAP.RANGE" %in% names(si))) {
    stop("`GAP.RANGE` column not found for alpha_code: ", code)
  }

  gap_range <- as.character(si[["GAP.RANGE"]])[1]
  if (!nzchar(gap_range) || is.na(gap_range)) {
    stop("Missing GAP.RANGE for alpha_code: ", code)
  }

  cat("------------------------------------------------------------------------\n")
  cat("plot_trend(): starting (divergent colors)\n")

  ## --------------------------- Paths -------------------------------------- ##
  data_dir    <- file.path(rENM_project_dir(), "data")
  states_path <- file.path(data_dir, "shapefiles", "tl_2012_us_state", "tl_2012_us_state.shp")

  if (!file.exists(states_path)) {
    stop("States shapefile not found: ", states_path)
  }

  range_dir  <- file.path(data_dir, "shapefiles", gap_range)
  range_path <- file.path(range_dir, paste0(gap_range, ".shp"))

  if (!file.exists(range_path)) {
    stop("Species range shapefile not found at: ", range_path)
  }

  ## ----------------------------- Load raster ------------------------------ ##
  if (inherits(raster_file, "SpatRaster")) {
    r <- raster_file
  } else if (is.character(raster_file) && length(raster_file) == 1L) {
    if (!file.exists(raster_file)) {
      stop("Trend raster file not found: ", raster_file)
    }
    r <- terra::rast(raster_file)
  } else if (inherits(raster_file, c("RasterLayer", "RasterStack", "RasterBrick"))) {
    r <- terra::rast(raster_file)
  } else {
    stop("`raster_file` must be a terra::SpatRaster, a raster::Raster*, or a file path.")
  }

  if (terra::nlyr(r) > 1L) {
    r <- r[[1L]]
  }

  r_df <- terra::as.data.frame(r, xy = TRUE, na.rm = TRUE)
  if (!nrow(r_df)) {
    stop("Trend raster has no non-NA cells; cannot plot.", call. = FALSE)
  }
  names(r_df)[3] <- "trend"
  n_cells <- nrow(r_df)

  ## --------------------- Limits & color scaling --------------------------- ##
  rng <- stats::quantile(r_df$trend, probs = c(0.02, 0.98), na.rm = TRUE, names = FALSE)
  max_abs <- max(abs(rng), na.rm = TRUE)
  if (!is.finite(max_abs) || max_abs <= 0) {
    max_abs <- max(abs(r_df$trend), na.rm = TRUE)
  }
  if (!is.finite(max_abs) || max_abs <= 0) {
    stop("Trend values are all zero or NA; nothing to plot.", call. = FALSE)
  }

  zero_band_frac <- max(0, min(0.90, zero_band_frac))
  lims <- c(-max_abs, max_abs)

  ## -------------------------- Vectors & reproj ---------------------------- ##
  stl <- terra::vect(states_path)
  spv <- terra::vect(range_path)

  if (!is.na(terra::crs(r))) {
    if (!terra::same.crs(stl, r)) stl <- terra::project(stl, r)
    if (!terra::same.crs(spv, r)) spv <- terra::project(spv, r)
  }

  states <- sf::st_as_sf(stl)
  range  <- sf::st_as_sf(spv)

  ## ------------------------- Extent & paddings ---------------------------- ##
  ex <- terra::ext(r)
  dx <- ex$xmax - ex$xmin
  dy <- ex$ymax - ex$ymin
  pad <- 0.02
  xlim <- c(ex$xmin - pad * dx, ex$xmax + pad * dx)
  ylim <- c(ex$ymin - pad * dy, ex$ymax + pad * dy)

  ## ------------------------------ Plot ------------------------------------ ##
  gp <- ggplot2::ggplot() +
    ggplot2::geom_raster(
      data = r_df,
      mapping = ggplot2::aes(x = x, y = y, fill = trend)
    ) +
    ggplot2::geom_sf(data = states, fill = NA, color = "grey40", linewidth = 0.3) +
    ggplot2::geom_sf(data = range,  fill = NA, color = "black",  linewidth = 0.7) +

    # ggplot2::scale_fill_gradient2(
    #   name     = "Trend",
    #   low      = "#D64241",
    #   mid      = "white",
    #   high     = "#58B440",
    #   midpoint = 0,
    #   limits   = lims
    # ) +

    ggplot2::scale_fill_gradient2(
      name = "Trend",
      low = "#D64241",
      mid = "white",
      high = "#58B440",
      midpoint = 0,
      limits = lims,
      oob = scales::squish,     # prevents gray artifacts
      na.value = "transparent"  # optional cleanup
    ) +

    ggplot2::coord_sf(xlim = xlim, ylim = ylim, expand = FALSE) +
    ggplot2::labs(
      title = paste(code, "Climatic Suitability Trend"),
      subtitle = "1980-2020",
      x = "Longitude",
      y = "Latitude"
    ) +
    ggplot2::theme_minimal(base_size = 13) +
    ggplot2::theme(
      panel.background  = ggplot2::element_rect(fill = "grey98", color = NA),
      panel.border      = ggplot2::element_rect(color = "grey30", fill = NA, linewidth = 0.6),
      panel.grid.major  = ggplot2::element_line(linewidth = 0.3, color = "grey88"),
      panel.grid.minor  = ggplot2::element_blank(),
      axis.title        = ggplot2::element_text(face = "plain"),
      axis.text         = ggplot2::element_text(color = "grey20"),
      legend.title      = ggplot2::element_text(size = 9),
      legend.text       = ggplot2::element_text(size = 8),
      legend.key.height = ggplot2::unit(1.0, "lines"),
      legend.key.width  = ggplot2::unit(0.4, "lines"),
      legend.position   = "right",
      plot.title        = ggplot2::element_text(face = "bold", size = 12, hjust = 0)
    )

  cat(sprintf("Cells plotted: %s\n", format(n_cells, big.mark = ",", scientific = FALSE)))
  cat("plot_trend(): done. Returning ggplot object.\n")

  invisible(list(plot = gp, lims = lims, n_cells = n_cells))
}
